# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: c6be83bd7e95d5644a07448dc6572fc9d5f02f7219265be00290116087073bd9475bbaa69865447598a0bacbe64ff09cac8f85c2a0b50e5e4ee0bddb3f4c6893

test:
  secret_key_base: 1790f546678dcd1345d9ba2fd6f034b00dc150135ecd239d8e96616439b6ffd976d8730856a781234ab598cfc095e7f4ecf1b985034dae96435c8ed2463a659b

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
